baseURL = 'https://red-sea-0b5a48603.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'Laurence Tickell'
theme = "ananke"
googleAnalytics = ""
enableRobotsTXT = true





[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/LaurenceTickell"
[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/laurence-carton-tickell/"
[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/laurence262/"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/lazmac3"
