baseURL = 'https://red-sea-0b5a48603.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'Laurence Tickell'
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/LaurenceTickell"
[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/laurence-carton-tickell/"
[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/laurence262/reels/"
