baseURL = 'https://red-sea-0b5a48603.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'Laurence Tickell'
theme = "ananke"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO1"
